### PR TITLE
Added Haskell repository.

### PR DESCRIPTION
**Pull request by rdnetto**
This PR adds an SCR for the haskell overlay.

### CODE REVIEW

**Comment by mudler** [comment]
ok for me, one thing only: why build against weekly? currently all SCR is built against main
consider also that you may need to maintain that repo as well :)

**Comment by rdnetto** [comment]
> why build against weekly? currently all SCR is built against main

I wanted to be as conservative as possible in depending on newer versions, especially as the system I use at work is on weekly, to reduce the likelihood of broken updates.

> consider also that you may need to maintain that repo as well :)

I'm fine with that, it'll be less effort than trying to maintain mixed entropy/portage installs on multiple different systems. :P

**Comment by rdnetto** [comment]
Note: I've amended the PR to prevent it from pulling dependencies from Entropy, as it was otherwise attempting to install Haskell libraries (which were compiled against a different version of GHC) and then emerge them on top of that.

The CI build indicates it's not emerging anything outside of dev-haskell/ (apart from dev-lang/ghc), so this should be fine.

**Comment by mudler** [comment]
Need to wait for next round of updates before merging this, thanks for your contribution :)
For the next times: please suffix the repository name in the commit messages (e.g. **[haskell]** _Disabling pulling deps..._ )

**Comment by rdnetto** [comment]
No problem. :)
Will keep that in mind - just rebased the commits to include the prefix.

**Pull request merged**
